MODEL:
  META_ARCHITECTURE: "fcn32s"

  BACKBONE:
    PRETRAINED: False

  REFINEMENT:
    NAME: ''

DATASETS:
  ROOT: 'C:/Users/ZOE ZHAO/Documents/fcn.pytorch/dataset/VOCdevkit/VOC2012'


TEST:
  WEIGHT: 'C:/Users/ZOE ZHAO/Documents/fcn.pytorch/train_fcn32s/fcn_model_13.pth'

OUTPUT_DIR: "C:/Users/ZOE ZHAO/Documents/fcn.pytorch/inference_fcn32s"

